/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.buildcostaffapplication.view;

import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.buildcostaffapplication.controller.EnquiryController;
import lk.buildcostaffapplication.controller.ItemController;
import lk.buildcostaffapplication.dto.EnquiryDTO;
import lk.buildcostaffapplication.dto.ItemDTO;

/**
 *
 * @author Binath Perera
 */
public class EnquiriesPanel extends javax.swing.JPanel {

    /**
     * Creates new form InquiriesPanel
     */
    String id;
    String ids[];
    EnquiryController controller;
    ItemController itemController;
    public EnquiriesPanel() {
        initComponents();
        cancelSelectionButton.setEnabled(false);
        updateButton.setEnabled(false);
        addButton.setEnabled(true);
        addItemButton.setEnabled(true);
        deleteEnquiryButton.setEnabled(false);
        controller= new EnquiryController();
        itemController=new ItemController();
        openEnquiriesTextField.setText(""+controller.getOpenEnquiryCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openEnquiriesLabel = new javax.swing.JLabel();
        openEnquiriesTextField = new javax.swing.JTextField();
        searchPanel = new javax.swing.JPanel();
        timeComboBox = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchResultsTable = new javax.swing.JTable();
        deleteEnquiryButton = new javax.swing.JButton();
        cancelSelectionButton = new javax.swing.JButton();
        fromDateChooser = new com.toedter.calendar.JDateChooser();
        toDateChooser = new com.toedter.calendar.JDateChooser();
        fromDateLabel = new javax.swing.JLabel();
        toDateLabel = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        timeLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        nicORemailLabel = new javax.swing.JLabel();
        nicORemailTextField = new javax.swing.JTextField();
        enquiryDetailsPanel = new javax.swing.JPanel();
        fullNameLabel = new javax.swing.JLabel();
        companyNameLabel = new javax.swing.JLabel();
        telephoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        solvedCheckBox = new javax.swing.JCheckBox();
        updateButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        fullNameTextField = new javax.swing.JTextField();
        companyNameTextField = new javax.swing.JTextField();
        telephoneTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        locationOfHireTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        responseLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        responseTextArea = new javax.swing.JTextArea();
        nicLabel = new javax.swing.JLabel();
        nicTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        enquiryItemsTable = new javax.swing.JTable();
        removeItemButton = new javax.swing.JButton();
        skuLabel = new javax.swing.JLabel();
        skuTextField = new javax.swing.JTextField();
        addItemButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(971, 1000));

        openEnquiriesLabel.setText("Open enquiries");

        openEnquiriesTextField.setEditable(false);

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        timeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All time", "Time Period", " " }));

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Customer Name", "Company Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        searchResultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(searchResultsTable);

        deleteEnquiryButton.setText("Remove Details of this Enquiry");
        deleteEnquiryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEnquiryButtonActionPerformed(evt);
            }
        });

        cancelSelectionButton.setText("Cancel Selection");
        cancelSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSelectionButtonActionPerformed(evt);
            }
        });

        fromDateLabel.setText("From");

        toDateLabel.setText("To");

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open", "Closed", "Both" }));

        timeLabel.setText("Time");

        statusLabel.setText("Status");

        nicORemailLabel.setText("Customer NIC/Email");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(timeLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addGap(58, 58, 58)
                        .addComponent(nicORemailLabel))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nicORemailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromDateLabel))
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toDateLabel)
                    .addComponent(toDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addGap(18, 18, 18))
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap(608, Short.MAX_VALUE)
                .addComponent(cancelSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteEnquiryButton)
                .addGap(11, 11, 11))
            .addComponent(jScrollPane2)
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(searchPanelLayout.createSequentialGroup()
                            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(timeLabel)
                                .addComponent(statusLabel)
                                .addComponent(nicORemailLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nicORemailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(toDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromDateLabel)
                            .addComponent(toDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEnquiryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        enquiryDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Enquiry Details"));

        fullNameLabel.setText("Full Name *");

        companyNameLabel.setText(" Company Name");

        telephoneLabel.setText("Telephone *");

        emailLabel.setText("Email ");

        locationLabel.setText("Location of hire *");

        messageLabel.setText("Message *");

        solvedCheckBox.setText("Mark as solved");

        updateButton.setText("Update Enquiry");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add this Enquiry");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        telephoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneTextFieldActionPerformed(evt);
            }
        });

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        responseLabel.setText("Briefly State Your Response");

        responseTextArea.setColumns(20);
        responseTextArea.setRows(5);
        jScrollPane3.setViewportView(responseTextArea);

        nicLabel.setText("NIC");

        enquiryItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SKU", "Name"
            }
        ));
        jScrollPane4.setViewportView(enquiryItemsTable);

        removeItemButton.setText("Remove selected item from list");
        removeItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemButtonActionPerformed(evt);
            }
        });

        skuLabel.setText("SKU");

        addItemButton.setText("Add this item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enquiryDetailsPanelLayout = new javax.swing.GroupLayout(enquiryDetailsPanel);
        enquiryDetailsPanel.setLayout(enquiryDetailsPanelLayout);
        enquiryDetailsPanelLayout.setHorizontalGroup(
            enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enquiryDetailsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enquiryDetailsPanelLayout.createSequentialGroup()
                        .addComponent(skuLabel)
                        .addGap(18, 18, 18)
                        .addComponent(skuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addItemButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(enquiryDetailsPanelLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(solvedCheckBox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(enquiryDetailsPanelLayout.createSequentialGroup()
                        .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(enquiryDetailsPanelLayout.createSequentialGroup()
                                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fullNameLabel)
                                    .addComponent(companyNameLabel)
                                    .addComponent(telephoneLabel)
                                    .addComponent(locationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(enquiryDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(fullNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                        .addGap(415, 415, 415)
                                        .addComponent(removeItemButton))
                                    .addGroup(enquiryDetailsPanelLayout.createSequentialGroup()
                                        .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(locationOfHireTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                            .addComponent(telephoneTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(42, 42, 42)
                                        .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nicLabel)
                                            .addComponent(emailLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailTextField)
                                            .addComponent(nicTextField)))
                                    .addComponent(companyNameTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enquiryDetailsPanelLayout.createSequentialGroup()
                                .addComponent(updateButton)
                                .addGap(18, 18, 18)
                                .addComponent(addButton))
                            .addGroup(enquiryDetailsPanelLayout.createSequentialGroup()
                                .addComponent(responseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane3)))
                            .addComponent(jScrollPane4))
                        .addContainerGap())))
        );
        enquiryDetailsPanelLayout.setVerticalGroup(
            enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enquiryDetailsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skuLabel)
                    .addComponent(skuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enquiryDetailsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fullNameLabel)
                            .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(enquiryDetailsPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(removeItemButton)))
                .addGap(18, 18, 18)
                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameLabel)
                    .addComponent(companyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailLabel)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(telephoneLabel))
                .addGap(18, 18, 18)
                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationOfHireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicLabel)
                    .addComponent(nicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(responseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(solvedCheckBox)
                .addGap(13, 13, 13)
                .addGroup(enquiryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(addButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(openEnquiriesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openEnquiriesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(enquiryDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openEnquiriesLabel)
                    .addComponent(openEnquiriesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enquiryDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        deleteEnquiryButton.setEnabled(false);
        cancelSelectionButton.setEnabled(false);
        updateButton.setEnabled(false);
        addButton.setEnabled(true);
        addItemButton.setEnabled(true);

        int timeIndex = timeComboBox.getSelectedIndex();
        int statusIndex = statusComboBox.getSelectedIndex();
        String nicOrEmail = nicORemailTextField.getText();
        Date from = fromDateChooser.getDate();
        Date to = toDateChooser.getDate();
        LocalDate fromDate=null;
        if(from!=null)fromDate=LocalDate.parse(from.toInstant().atZone(ZoneId.of("GMT")).format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));
        LocalDate toDate=null;
        if(to!=null)toDate=LocalDate.parse(to.toInstant().atZone(ZoneId.of("GMT")).format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));
        if(timeIndex==1 &&(fromDate==null || toDate==null)){
            JOptionPane.showMessageDialog(this, "Please enter the time period");
            return;
        }
        DefaultTableModel dtm=(DefaultTableModel)searchResultsTable.getModel();
        dtm.setRowCount(0);
        ArrayList<EnquiryDTO> arr= controller.search(timeIndex,statusIndex,nicOrEmail,fromDate,toDate);
        ids=new String[arr.size()];
        for(int i=0;i<arr.size();i++){
            EnquiryDTO enquiry= arr.get(i);
            ids[i]=enquiry.getId();
            dtm.addRow(new Object[]{enquiry.getDate().toString(),enquiry.getCustomerName(),enquiry.getCompanyName(),enquiry.getStatus()});
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchResultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultsTableMouseClicked
        cancelSelectionButton.setEnabled(true);
        deleteEnquiryButton.setEnabled(true);
        updateButton.setEnabled(true);
        addButton.setEnabled(false);
        addItemButton.setEnabled(true);
        int selectedRow = searchResultsTable.getSelectedRow();
        String ID= ids[selectedRow];
        EnquiryDTO enquiry = controller.getEnquiryByID(ID);
        id=ID;
        fullNameTextField.setText(enquiry.getCustomerName());
        companyNameTextField.setText(enquiry.getCompanyName());
        telephoneTextField.setText(enquiry.getTelephone());
        emailTextField.setText(enquiry.getEmail());
        locationOfHireTextField.setText(enquiry.getLocationOfHire());
        nicTextField.setText(enquiry.getNic());
        responseTextArea.setText(enquiry.getResponse());
        messageTextArea.setText(enquiry.getMessage());
        if(enquiry.getStatus().equals("closed"))solvedCheckBox.setSelected(true);
        else solvedCheckBox.setSelected(false);
        DefaultTableModel dtm=(DefaultTableModel)enquiryItemsTable.getModel();
        dtm.setRowCount(0);
        ArrayList<String> itemList = enquiry.getItemList();
        for(String sku: itemList){
            dtm.addRow(new Object[]{sku,itemController.getItemBySKU(sku).getName()});
        }
    }//GEN-LAST:event_searchResultsTableMouseClicked

    private void deleteEnquiryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEnquiryButtonActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Delete this enquiry?");
        if(showConfirmDialog!=0){return;}
        cancelSelectionButton.setEnabled(false);
        updateButton.setEnabled(false);
        addButton.setEnabled(true);
        addItemButton.setEnabled(true);
        deleteEnquiryButton.setEnabled(false);
        int selectedRow = searchResultsTable.getSelectedRow();
        if(selectedRow==-1){
            return;
        }
        boolean status=controller.deleteEnquiry(ids[selectedRow-1]);
        if(status){
            JOptionPane.showMessageDialog(this, "Deleted enquiry");
            DefaultTableModel model = (DefaultTableModel)searchResultsTable.getModel();
            model.removeRow(selectedRow);
            deleteEnquiryButton.setEnabled(false);
            clearForm();
            openEnquiriesTextField.setText(""+controller.getOpenEnquiryCount());
        }else{
            JOptionPane.showMessageDialog(this, "Failed to delete enquiry");
        }
    }//GEN-LAST:event_deleteEnquiryButtonActionPerformed
    private void clearForm(){
    
    }
    private void cancelSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSelectionButtonActionPerformed
        cancelSelectionButton.setEnabled(false);
        updateButton.setEnabled(false);
        addButton.setEnabled(true);
        addItemButton.setEnabled(true);
        deleteEnquiryButton.setEnabled(false);
        searchResultsTable.clearSelection();
    }//GEN-LAST:event_cancelSelectionButtonActionPerformed

    private void telephoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        LocalDate date= LocalDate.now();
        String customerName= fullNameTextField.getText();
        String companyName= companyNameTextField.getText();
        String telephone= telephoneTextField.getText();
        String locationOfHire= locationOfHireTextField.getText();
        String status= solvedCheckBox.isSelected()?"closed":"open";
        String email=emailTextField.getText();
        String nic= nicTextField.getText();
        String message= messageTextArea.getText();
        String response= responseTextArea.getText();
        int numOfRows= enquiryItemsTable.getRowCount();
        DefaultTableModel dtm=(DefaultTableModel)enquiryItemsTable.getModel();
        ArrayList<String> items=new ArrayList<>();
        for(int i=0;i<numOfRows;i++){
            items.add((String)dtm.getValueAt(i, 0));
        }
        boolean result=controller.addEnquiry(new EnquiryDTO(date, customerName, companyName, telephone, locationOfHire, status, email, nic, message, response, items));
        if(result){
            JOptionPane.showMessageDialog(this, "Enquiry added");
            openEnquiriesTextField.setText(""+controller.getOpenEnquiryCount());
        }else{
            JOptionPane.showMessageDialog(this, "Failed to add enquiry");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemButtonActionPerformed
        int selectedRow=enquiryItemsTable.getSelectedRow();
        DefaultTableModel dtm= (DefaultTableModel) enquiryItemsTable.getModel();
        dtm.removeRow(selectedRow);
    }//GEN-LAST:event_removeItemButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        LocalDate date= LocalDate.now();
        String customerName= fullNameTextField.getText();
        String companyName= companyNameTextField.getText();
        String telephone= telephoneTextField.getText();
        String locationOfHire= locationOfHireTextField.getText();
        String status= solvedCheckBox.isSelected()?"closed":"open";
        String email=emailTextField.getText();
        String nic= nicTextField.getText();
        String message= messageTextArea.getText();
        String response= responseTextArea.getText();
        int numOfRows= enquiryItemsTable.getRowCount();
        DefaultTableModel dtm=(DefaultTableModel)enquiryItemsTable.getModel();
        ArrayList<String> items=new ArrayList<>();
        for(int i=0;i<numOfRows;i++){
            items.add((String)dtm.getValueAt(i, 0));
        }
        boolean result=controller.updateEnquiry(new EnquiryDTO(id,date, customerName, companyName, telephone, locationOfHire, status, email, nic, message, response, items));
        if(result){
            JOptionPane.showMessageDialog(this, "Enquiry updated");
            openEnquiriesTextField.setText(""+controller.getOpenEnquiryCount());
        }else{
            JOptionPane.showMessageDialog(this, "Failed to update enquiry");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        String sku=skuTextField.getText();
        ItemDTO item = itemController.getItemBySKU(sku);
        if(item==null){
            JOptionPane.showMessageDialog(this, "No such item");
            return;
        }
        DefaultTableModel dtm= (DefaultTableModel) enquiryItemsTable.getModel();
        dtm.addRow(new Object[]{sku,item.getName()});
    }//GEN-LAST:event_addItemButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton cancelSelectionButton;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JTextField companyNameTextField;
    private javax.swing.JButton deleteEnquiryButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel enquiryDetailsPanel;
    private javax.swing.JTable enquiryItemsTable;
    private com.toedter.calendar.JDateChooser fromDateChooser;
    private javax.swing.JLabel fromDateLabel;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationOfHireTextField;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JLabel nicLabel;
    private javax.swing.JLabel nicORemailLabel;
    private javax.swing.JTextField nicORemailTextField;
    private javax.swing.JTextField nicTextField;
    private javax.swing.JLabel openEnquiriesLabel;
    private javax.swing.JTextField openEnquiriesTextField;
    private javax.swing.JButton removeItemButton;
    private javax.swing.JLabel responseLabel;
    private javax.swing.JTextArea responseTextArea;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable searchResultsTable;
    private javax.swing.JLabel skuLabel;
    private javax.swing.JTextField skuTextField;
    private javax.swing.JCheckBox solvedCheckBox;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JComboBox<String> timeComboBox;
    private javax.swing.JLabel timeLabel;
    private com.toedter.calendar.JDateChooser toDateChooser;
    private javax.swing.JLabel toDateLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
