/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.buildcostaffapplication.view;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.buildcostaffapplication.controller.ItemController;
import lk.buildcostaffapplication.dto.ItemDTO;

/**
 *
 * @author Binath Perera
 */
public class ItemsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemsPanel
     */
    ItemController controller;
    public ItemsPanel() {
        initComponents();
        controller=new ItemController();
        deleteItemButton.setEnabled(false);
        cancelButton.setEnabled(false);
        updateButton.setEnabled(false);
        addItemButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchComboBox = new javax.swing.JComboBox<>();
        searchBarTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        searchResultsTable = new javax.swing.JTable();
        deleteItemButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        itemDetailsPanel = new javax.swing.JPanel();
        skuLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        overviewLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        skuTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        currentValueLabel = new javax.swing.JLabel();
        overviewTextField = new javax.swing.JTextField();
        depotTextField = new javax.swing.JTextField();
        depotLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        attachmentsTextField = new javax.swing.JTextField();
        attachmentsLabel = new javax.swing.JLabel();
        safetyEquipmentLabel = new javax.swing.JLabel();
        safetyEquipmentTextField = new javax.swing.JTextField();
        specificationsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        specificationsTextArea = new javax.swing.JTextArea();
        imageUploadButton = new javax.swing.JButton();
        imageNameLabel = new javax.swing.JLabel();
        imageViewButton = new javax.swing.JButton();
        imageRemoveButton = new javax.swing.JButton();
        userManualUploadButton = new javax.swing.JButton();
        userManualFileNameLabel = new javax.swing.JLabel();
        userManualViewButton = new javax.swing.JButton();
        userManualRemoveButton = new javax.swing.JButton();
        serviceManualUploadButton = new javax.swing.JButton();
        serviceManualFileNameLabel = new javax.swing.JLabel();
        serviceManualViewButton = new javax.swing.JButton();
        serviceManualRemoveButton = new javax.swing.JButton();
        userManualLabel = new javax.swing.JLabel();
        serviceManualLabel = new javax.swing.JLabel();
        avaliableQuantityLabel = new javax.swing.JLabel();
        availableQuantityTextField = new javax.swing.JTextField();
        originalValueLabel = new javax.swing.JLabel();
        originalValueTextField = new javax.swing.JTextField();
        currentValueTextField = new javax.swing.JTextField();
        totalQuantityLabel = new javax.swing.JLabel();
        totalQuantityTextField = new javax.swing.JTextField();
        qtyChangeSpinner = new javax.swing.JSpinner();
        qtyChangeLabel = new javax.swing.JLabel();
        rateLabel = new javax.swing.JLabel();
        rateTextField = new javax.swing.JTextField();

        jLabel13.setText("jLabel13");

        setPreferredSize(new java.awt.Dimension(1047, 900));

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        searchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Get all", "SKU", "Name", " " }));

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SKU", "Item Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        searchResultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultsTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchResultsTableMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(searchResultsTable);

        deleteItemButton.setText("Remove this item");
        deleteItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel Selection");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBarTextField)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton)
                        .addGap(16, 16, 16))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Details"));

        skuLabel.setText("SKU");

        nameLabel.setText("Name");

        overviewLabel.setText("Overview");

        imageLabel.setText("Image");

        currentValueLabel.setText("Current value");

        depotLabel.setText("Depot");

        updateButton.setText("Update Item Details");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        attachmentsLabel.setText("Attachments");

        safetyEquipmentLabel.setText("Safety Equipment");

        specificationsLabel.setText("Specifications");

        specificationsTextArea.setColumns(20);
        specificationsTextArea.setRows(5);
        jScrollPane1.setViewportView(specificationsTextArea);

        imageUploadButton.setText("Upload");
        imageUploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageUploadButtonActionPerformed(evt);
            }
        });

        imageViewButton.setText("View");
        imageViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageViewButtonActionPerformed(evt);
            }
        });

        imageRemoveButton.setText("Remove");
        imageRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageRemoveButtonActionPerformed(evt);
            }
        });

        userManualUploadButton.setText("Upload");
        userManualUploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManualUploadButtonActionPerformed(evt);
            }
        });

        userManualViewButton.setText("View");
        userManualViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManualViewButtonActionPerformed(evt);
            }
        });

        userManualRemoveButton.setText("Remove");
        userManualRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManualRemoveButtonActionPerformed(evt);
            }
        });

        serviceManualUploadButton.setText("Upload");
        serviceManualUploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceManualUploadButtonActionPerformed(evt);
            }
        });

        serviceManualViewButton.setText("View");
        serviceManualViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceManualViewButtonActionPerformed(evt);
            }
        });

        serviceManualRemoveButton.setText("Remove");
        serviceManualRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceManualRemoveButtonActionPerformed(evt);
            }
        });

        userManualLabel.setText("User Manual");

        serviceManualLabel.setText("Service Manual");

        avaliableQuantityLabel.setText("Available Quantity");

        availableQuantityTextField.setEditable(false);

        originalValueLabel.setText("Original Value");

        totalQuantityLabel.setText("Total Quantity");

        totalQuantityTextField.setEditable(false);

        qtyChangeLabel.setText("Qty change");

        rateLabel.setText("Rate(Per day)");

        javax.swing.GroupLayout itemDetailsPanelLayout = new javax.swing.GroupLayout(itemDetailsPanel);
        itemDetailsPanel.setLayout(itemDetailsPanelLayout);
        itemDetailsPanelLayout.setHorizontalGroup(
            itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(overviewLabel)
                                    .addComponent(nameLabel)
                                    .addComponent(specificationsLabel)
                                    .addComponent(attachmentsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(overviewTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(nameTextField))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(safetyEquipmentLabel)
                                        .addGap(18, 18, 18)
                                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(attachmentsTextField)
                                            .addComponent(safetyEquipmentTextField)))
                                    .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(currentValueLabel)
                                            .addComponent(originalValueLabel)
                                            .addComponent(qtyChangeLabel)
                                            .addComponent(rateLabel))
                                        .addGap(37, 37, 37)
                                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(originalValueTextField)
                                            .addComponent(currentValueTextField)
                                            .addComponent(qtyChangeSpinner)
                                            .addComponent(rateTextField))))
                                .addGap(30, 30, 30)
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(imageLabel)
                                        .addGap(85, 85, 85)
                                        .addComponent(imageUploadButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageViewButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageRemoveButton))
                                    .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                                .addComponent(serviceManualLabel)
                                                .addGap(38, 38, 38)
                                                .addComponent(serviceManualUploadButton))
                                            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                                .addComponent(userManualLabel)
                                                .addGap(52, 52, 52)
                                                .addComponent(userManualUploadButton)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                                .addComponent(userManualFileNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(userManualViewButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(userManualRemoveButton))
                                            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                                .addComponent(serviceManualFileNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(serviceManualViewButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(serviceManualRemoveButton))))))
                            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                .addComponent(skuLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(skuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depotLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depotTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalQuantityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(avaliableQuantityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(availableQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        itemDetailsPanelLayout.setVerticalGroup(
            itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skuLabel)
                    .addComponent(skuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depotLabel)
                    .addComponent(depotTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avaliableQuantityLabel)
                    .addComponent(availableQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalQuantityLabel)
                    .addComponent(totalQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameLabel)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(overviewLabel)
                                    .addComponent(overviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(specificationsLabel))
                                    .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                                .addGap(17, 17, 17)
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(attachmentsLabel)
                                    .addComponent(attachmentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(safetyEquipmentLabel)
                                    .addComponent(safetyEquipmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(imageUploadButton)
                                    .addComponent(imageLabel))
                                .addComponent(imageNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(imageViewButton)
                                    .addComponent(imageRemoveButton))))
                        .addGap(18, 18, 18)
                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(userManualUploadButton)
                                .addComponent(userManualLabel))
                            .addComponent(userManualFileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(userManualViewButton)
                                .addComponent(userManualRemoveButton)))
                        .addGap(18, 18, 18)
                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serviceManualUploadButton)
                            .addComponent(serviceManualFileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(serviceManualViewButton)
                                .addComponent(serviceManualRemoveButton))))
                    .addGroup(itemDetailsPanelLayout.createSequentialGroup()
                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(originalValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(originalValueLabel))
                        .addGap(18, 18, 18)
                        .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serviceManualLabel)
                            .addComponent(currentValueLabel)
                            .addComponent(currentValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyChangeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyChangeLabel))
                .addGap(18, 18, 18)
                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateLabel)
                    .addComponent(rateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(itemDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        deleteItemButton.setEnabled(false);
        cancelButton.setEnabled(false);
        updateButton.setEnabled(false);
        addItemButton.setEnabled(true);
        searchResultsTable.clearSelection();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        deleteItemButton.setEnabled(false);
        cancelButton.setEnabled(false);
        updateButton.setEnabled(false);
        addItemButton.setEnabled(true);

        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Delete this item?");
        if(showConfirmDialog!=0){return;}
        int selectedRow = searchResultsTable.getSelectedRow();
        if(selectedRow==-1){
            return;
        }
        boolean status=controller.deleteItem(String.valueOf(searchResultsTable.getValueAt(selectedRow, 0)));
        if(status){
            JOptionPane.showMessageDialog(this, "Deleted item");
            DefaultTableModel model = (DefaultTableModel)searchResultsTable.getModel();
            model.removeRow(selectedRow);
            deleteItemButton.setEnabled(false);
            skuTextField.setEditable(true);
            clearForm();
        }else{
            JOptionPane.showMessageDialog(this, "Failed to delete item");
        }
    }//GEN-LAST:event_deleteUserButtonActionPerformed

    private void searchResultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultsTableMouseClicked
        cancelButton.setEnabled(true);
        deleteItemButton.setEnabled(true);
        updateButton.setEnabled(true);
        addItemButton.setEnabled(false);

        int selectedRow = searchResultsTable.getSelectedRow();
        String sku= String.valueOf(searchResultsTable.getValueAt(selectedRow,0));
        ItemDTO item=controller.getItemBySKU(sku);
        skuTextField.setText(item.getSku());
        depotTextField.setText(item.getDepot());
        nameTextField.setText(item.getName());
        overviewTextField.setText(item.getOverview());
        specificationsTextArea.setText(item.getSpecifications());
        attachmentsTextField.setText(item.getAttachments());
        safetyEquipmentTextField.setText(item.getSafetyEquipment());
        totalQuantityTextField.setText(""+item.getTotalQty());
        availableQuantityTextField.setText(""+item.getExistingQty());
        originalValueTextField.setText(""+item.getOriginalVal());
        currentValueTextField.setText(""+item.getCurrentVal());
        image=item.getImage();
        serviceManual=item.getServiceManual();
        userManual=item.getUserManual();
        imageNameLabel.setText(image.getName());
        serviceManualFileNameLabel.setText(serviceManual.getName());
        userManualFileNameLabel.setText(userManual.getName());
        qtyChangeSpinner.setValue(0);
        rateTextField.setText(""+item.getRate());
    }//GEN-LAST:event_searchResultsTableMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        deleteItemButton.setEnabled(false);
        cancelButton.setEnabled(false);
        updateButton.setEnabled(false);
        addItemButton.setEnabled(true);
        int index = searchComboBox.getSelectedIndex();
        String searchItem = searchBarTextField.getText();
        DefaultTableModel dtm=(DefaultTableModel)searchResultsTable.getModel();
        dtm.setRowCount(0);
        ArrayList<ItemDTO> allItems;
        if(index==0){
            allItems= controller.getItemSKUsAndNames();
            for(ItemDTO item: allItems){
                String SKU = item.getSku();
                String name = item.getName();
                dtm.addRow(new Object[]{SKU,name});
            }
        }else if(index==1){
            ItemDTO item= controller.getItemBySKU(searchBarTextField.getText());
            String SKU = item.getSku();
            String name = item.getName();
            dtm.addRow(new Object[]{SKU,name});
        }  
    }//GEN-LAST:event_searchButtonActionPerformed

    private void serviceManualRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceManualRemoveButtonActionPerformed
        serviceManual = null;
        serviceManualFileNameLabel.setText("");
    }//GEN-LAST:event_serviceManualRemoveButtonActionPerformed

    private void serviceManualViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceManualViewButtonActionPerformed
        if(serviceManual==null){
            JOptionPane.showMessageDialog(this, "Upload service manual before viewing");
            return;
        }
        if(!Desktop.isDesktopSupported())//check if Desktop is supported by Platform or not
        {
            JOptionPane.showMessageDialog(this, "View Feature Not Supported");
            return;
        }
        Desktop desktop = Desktop.getDesktop();
        if(serviceManual.exists()){ //checks file exists or not
            try {
                desktop.open(serviceManual);//opens the specified file
            } catch (IOException ex) {
                Logger.getLogger(EmployeesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "File Does Not Exist");
        }
    }//GEN-LAST:event_serviceManualViewButtonActionPerformed

    private void serviceManualUploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceManualUploadButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showDialog(this,"Upload");
        if(returnVal==0){ //If file selected 0, otherwise 1
            serviceManual = fc.getSelectedFile();
            serviceManualFileNameLabel.setText(serviceManual.getName());
        }
    }//GEN-LAST:event_serviceManualUploadButtonActionPerformed

    private void userManualRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManualRemoveButtonActionPerformed
        userManual = null;
        userManualFileNameLabel.setText("");
    }//GEN-LAST:event_userManualRemoveButtonActionPerformed

    private void userManualViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManualViewButtonActionPerformed
        if(userManual==null){
            JOptionPane.showMessageDialog(this, "Upload user manual before viewing");
            return;
        }
        if(!Desktop.isDesktopSupported())//check if Desktop is supported by Platform or not
        {
            JOptionPane.showMessageDialog(this, "View Feature Not Supported");
            return;
        }
        Desktop desktop = Desktop.getDesktop();
        if(userManual.exists()){ //checks file exists or not
            try {
                desktop.open(userManual);//opens the specified file
            } catch (IOException ex) {
                Logger.getLogger(EmployeesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "File Does Not Exist");
        }
    }//GEN-LAST:event_userManualViewButtonActionPerformed

    private void userManualUploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManualUploadButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showDialog(this,"Upload");
        if(returnVal==0){ //If file selected 0, otherwise 1
            userManual = fc.getSelectedFile();
            userManualFileNameLabel.setText(userManual.getName());
        }
    }//GEN-LAST:event_userManualUploadButtonActionPerformed

    private void imageRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageRemoveButtonActionPerformed
        image = null;
        imageNameLabel.setText("");
    }//GEN-LAST:event_imageRemoveButtonActionPerformed

    private void imageViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageViewButtonActionPerformed
        if(image==null){
            JOptionPane.showMessageDialog(this, "Upload image Before Viewing");
            return;
        }
        if(!Desktop.isDesktopSupported())//check if Desktop is supported by Platform or not
        {
            JOptionPane.showMessageDialog(this, "View Feature Not Supported");
            return;
        }
        Desktop desktop = Desktop.getDesktop();
        if(image.exists()){ //checks file exists or not
            try {
                desktop.open(image);//opens the specified file
            } catch (IOException ex) {
                Logger.getLogger(EmployeesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "File Does Not Exist");
        }
    }//GEN-LAST:event_imageViewButtonActionPerformed
    File image=null;
    File userManual=null;
    File serviceManual=null;
    private void imageUploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageUploadButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showDialog(this,"Upload");
        if(returnVal==0){ //If file selected 0, otherwise 1
            image = fc.getSelectedFile();
            imageNameLabel.setText(image.getName());
        }
    }//GEN-LAST:event_imageUploadButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Add this item?");
        if(showConfirmDialog!=0){return;}
        String sku = skuTextField.getText();
        String depot = depotTextField.getText();
        String name = nameTextField.getText();
        String overview = overviewTextField.getText();
        String specifications = specificationsTextArea.getText();
        String attachments = attachmentsTextField.getText();
        String safetyEquipment = safetyEquipmentTextField.getText();
        
        int totalQty = 0;
        if(!totalQuantityTextField.getText().equals(""))totalQty=Integer.valueOf(totalQuantityTextField.getText());
        int existingQty = 0;
        if(!availableQuantityTextField.getText().equals(""))existingQty =Integer.valueOf(availableQuantityTextField.getText());
        int qtyChange = (int)qtyChangeSpinner.getValue();
        double originalVal = Double.valueOf(originalValueTextField.getText());
        double currentVal = Double.valueOf(currentValueTextField.getText());
        double rate = Double.valueOf(rateTextField.getText());
        ItemDTO item= new ItemDTO(sku, depot, name, overview, specifications, attachments, safetyEquipment, totalQty, existingQty, qtyChange, originalVal, currentVal, image, userManual, serviceManual,rate);  
        boolean status=controller.addItem(item);
        if(status){
            JOptionPane.showMessageDialog(this, "New item added");
            clearForm();
        }else{
            JOptionPane.showMessageDialog(this, "The item already exists");
        }
    }//GEN-LAST:event_addItemButtonActionPerformed
    
    private void clearForm(){
        
    }
    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Update this item?");
        if(showConfirmDialog!=0){return;}
        String sku = skuTextField.getText();
        String depot = depotTextField.getText();
        String name = nameTextField.getText();
        String overview = overviewTextField.getText();
        String specifications = specificationsTextArea.getText();
        String attachments = attachmentsTextField.getText();
        String safetyEquipment = safetyEquipmentTextField.getText();
        int totalQty = Integer.valueOf(totalQuantityTextField.getText());
        int existingQty = Integer.valueOf(availableQuantityTextField.getText());
        int qtyChange = (int)qtyChangeSpinner.getValue();
        double originalVal = Double.valueOf(originalValueTextField.getText());
        double currentVal = Double.valueOf(currentValueTextField.getText());
        double rate = Double.valueOf(rateTextField.getText());
        ItemDTO item= new ItemDTO(sku, depot, name, overview, specifications, attachments, safetyEquipment, totalQty, existingQty, qtyChange, originalVal, currentVal, image, userManual, serviceManual,rate);  
        boolean status=controller.updateItem(item);
        if(status){
            JOptionPane.showMessageDialog(this, "Item updated");
            clearForm();
        }else{
            JOptionPane.showMessageDialog(this, "Update failed !");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void searchResultsTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultsTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchResultsTableMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JLabel attachmentsLabel;
    private javax.swing.JTextField attachmentsTextField;
    private javax.swing.JTextField availableQuantityTextField;
    private javax.swing.JLabel avaliableQuantityLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel currentValueLabel;
    private javax.swing.JTextField currentValueTextField;
    private javax.swing.JButton deleteItemButton;
    private javax.swing.JLabel depotLabel;
    private javax.swing.JTextField depotTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel imageNameLabel;
    private javax.swing.JButton imageRemoveButton;
    private javax.swing.JButton imageUploadButton;
    private javax.swing.JButton imageViewButton;
    private javax.swing.JPanel itemDetailsPanel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel originalValueLabel;
    private javax.swing.JTextField originalValueTextField;
    private javax.swing.JLabel overviewLabel;
    private javax.swing.JTextField overviewTextField;
    private javax.swing.JLabel qtyChangeLabel;
    private javax.swing.JSpinner qtyChangeSpinner;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JTextField rateTextField;
    private javax.swing.JLabel safetyEquipmentLabel;
    private javax.swing.JTextField safetyEquipmentTextField;
    private javax.swing.JTextField searchBarTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchComboBox;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable searchResultsTable;
    private javax.swing.JLabel serviceManualFileNameLabel;
    private javax.swing.JLabel serviceManualLabel;
    private javax.swing.JButton serviceManualRemoveButton;
    private javax.swing.JButton serviceManualUploadButton;
    private javax.swing.JButton serviceManualViewButton;
    private javax.swing.JLabel skuLabel;
    private javax.swing.JTextField skuTextField;
    private javax.swing.JLabel specificationsLabel;
    private javax.swing.JTextArea specificationsTextArea;
    private javax.swing.JLabel totalQuantityLabel;
    private javax.swing.JTextField totalQuantityTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userManualFileNameLabel;
    private javax.swing.JLabel userManualLabel;
    private javax.swing.JButton userManualRemoveButton;
    private javax.swing.JButton userManualUploadButton;
    private javax.swing.JButton userManualViewButton;
    // End of variables declaration//GEN-END:variables
}
