/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.buildcostaffapplication.view;

import static java.lang.Thread.sleep;
import java.util.Random;
import javax.swing.JOptionPane;
import lk.buildcostaffapplication.controller.MainFrameGenerator;
import lk.buildcostaffapplication.controller.LoginController;
import lk.buildcostaffapplication.dto.LoginDTO;
import org.apache.commons.lang3.RandomStringUtils;

/**
 *
 * @author Binath Perera
 */

public class LoginPanel extends javax.swing.JPanel {
    /**
     * Creates new form LoginPanel
     */
    String tempPassword=null;
    String code=null;
    LoginController controller;
    public LoginPanel() {
        initComponents();
        controller=new LoginController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passwordTextField = new javax.swing.JPasswordField();
        builcoImageLabel = new javax.swing.JLabel();
        forgotPasswordButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(160, 141, 130));
        setForeground(new java.awt.Color(239, 246, 255));
        setMinimumSize(new java.awt.Dimension(338, 220));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(392, 552));

        usernameLabel.setBackground(new java.awt.Color(0, 0, 0));
        usernameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        usernameLabel.setText("Username");

        usernameTextField.setBackground(new java.awt.Color(255, 255, 255));
        usernameTextField.setColumns(15);
        usernameTextField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        usernameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        passwordLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(51, 51, 51));
        passwordLabel.setText("Password");

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 0, 0));
        loginButton.setText("Login");
        loginButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        passwordTextField.setBackground(new java.awt.Color(255, 255, 255));
        passwordTextField.setColumns(13);
        passwordTextField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        passwordTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        builcoImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buildco-login-image.png"))); // NOI18N

        forgotPasswordButton.setBackground(new java.awt.Color(160, 141, 130));
        forgotPasswordButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        forgotPasswordButton.setForeground(new java.awt.Color(0, 0, 204));
        forgotPasswordButton.setText("Forgot your password ?");
        forgotPasswordButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        forgotPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(builcoImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(forgotPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addComponent(passwordTextField))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(builcoImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forgotPasswordButton)
                .addGap(43, 43, 43)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private MainFrame mf;
    @SuppressWarnings("empty-statement")
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username=usernameTextField.getText();
        String password=passwordTextField.getText();
        LoginDTO result=controller.logUser(this,username,password);
        if(result!=null){
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run(){
                    mf= new MainFrameGenerator(result.getName(),result.getList()).getMf();
                    mf.setVisible(true);
                }
            });
            LoginFrame.getLoginFrame().close();
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        loginButton.setBackground(new java.awt.Color(82, 163, 133));
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited
        loginButton.setBackground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_loginButtonMouseExited
    
    private void generateTenMinutePassword(){       
        Thread c= new Thread(){
            @Override
            public void run(){
                
                try {
                    String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
                    tempPassword = RandomStringUtils.random( 8, characters );
                    sleep(600000);
                    tempPassword=null;
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
                
            }
        };
        c.start();
    }
    
    private void generateTenMinuteCode(){    
        Thread c= new Thread(){
            @Override
            public void run(){
                
                try {
                    Random rnd = new Random();
                    int number = rnd.nextInt(999999);
                    // this will convert any number sequence into 6 character.
                    code=String.format("%06d", number);
                    sleep(600000);
                    code=null;
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
                
            }
        };
        c.start();
    }
    
    private void forgotPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPasswordButtonActionPerformed
        // TODO add your handling code here:
        String ID=usernameTextField.getText();
        if(ID.trim().equals("") || ID==null){
            JOptionPane.showMessageDialog(this,"Please enter the username");
            return;
        }
        controller.forgotPassword(this,ID);
    }//GEN-LAST:event_forgotPasswordButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel builcoImageLabel;
    private javax.swing.JButton forgotPasswordButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
